apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: svc-mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30006
    protocol: TCP
  selector:
    app: pod-mysql
